- name: Ensure the src directory exists
  ansible.builtin.file:
    path: /home/almalinux/comp0239_cw/src
    state: directory
    mode: '0755'
  become: true
  
- name: Delete old slurm bash script #TEMPORARY
  ansible.builtin.file:
    path: /home/almalinux/comp0239_cw/src/submit_bash_parallel.sh
    state: absent
  become: true

- name: Copy the Slurm bash script 
  ansible.builtin.copy:
    src: /home/almalinux/comp0239_cw/src/submit_bash_parallel.sh
    dest: /home/almalinux/comp0239_cw/src/submit_bash_parallel.sh
    mode: '0755' # Crucial: Makes the bash script executable
  become: true

- name: Copy the launch script
  ansible.builtin.copy:
    src: /home/almalinux/comp0239_cw/src/launch_job.sh
    dest: /home/almalinux/comp0239_cw/src/launch_job.sh
    mode: '0755' # Crucial: Makes the bash script executable
  become: true