- name: Generate SSH key (only if it does not exist)
  ansible.builtin.command:
    cmd: ssh-keygen -q -t ed25519 -f /home/almalinux/.ssh/id_ed25519 -C "" -N ""
  args:
    creates: /home/almalinux/.ssh/id_ed25519 # The magic condition

- name: Read the public key into memory
  ansible.builtin.slurp:
    src: /home/almalinux/.ssh/id_ed25519.pub
  register: ssh_pub_key

- name: Add public key to authorized_keys (idempotent)
  ansible.builtin.lineinfile:
    path: /home/almalinux/.ssh/authorized_keys
    line: "{{ ssh_pub_key['content'] | b64decode | trim }}"
    create: true
    owner: almalinux
    mode: '0600'

- name: Get private key to controller
  ansible.builtin.fetch:
    src: /home/almalinux/.ssh/id_ed25519
    dest: ./.generated/temp_id_ed25519/
    flat: true

- name: Get public key to controller
  ansible.builtin.fetch:
    src: /home/almalinux/.ssh/id_ed25519.pub
    dest: ./.generated/temp_id_ed25519/
    flat: true

- name: Generate Munge key (only if it does not exist)
  ansible.builtin.command:
    cmd: create-munge-key
  args:
    creates: /etc/munge/munge.key # The magic condition
  become: true

- name: Get munge key to controller
  ansible.builtin.fetch:
    src: /etc/munge/munge.key
    dest: ./.generated/munge/
    flat: true
  become: true

- name: Start munge service
  ansible.builtin.systemd_service:
    name: munge
    state: started
    enabled: true
  become: true

- name: Add SSH config file
  ansible.builtin.copy:
    src: files/ssh_config
    dest: /home/almalinux/.ssh/config
    owner: almalinux
    mode: '0600'