- name: Ensure dataset directory exists on BeeGFS
  ansible.builtin.file:
    path: /beegfs/dataset
    state: directory
    mode: '0777'
  become: true

- name: Ensure results directory exists on BeeGFS
  ansible.builtin.file:
    path: /beegfs/results
    state: directory
    mode: '0777'
  become: true

- name: Install unzip
  ansible.builtin.dnf:
    name: unzip
    state: present
  become: true

- name: Read Kaggle credentials from local JSON file
  ansible.builtin.set_fact:
    kaggle_creds: "{{ lookup('file', 'kaggle.json') | from_json }}"
  delegate_to: localhost
  become: false

- name: Check if unzipped dataset already exists to avoid redundant download
  ansible.builtin.stat:
    path: /beegfs/dataset/TRAIN_V2
  register: dataset_stat

- name: Stream dataset directly to BeeGFS using curl
  ansible.builtin.command: >
    curl -L -u "{{ kaggle_creds.username }}:{{ kaggle_creds.key }}" 
    -o /beegfs/dataset/music-classification-wav.zip 
    https://www.kaggle.com/api/v1/datasets/download/asisheriberto/music-classification-wav
  args:
    creates: /beegfs/dataset/music-classification-wav.zip
  when: not dataset_stat.stat.exists
  become: true

- name: Extract dataset using native Linux unzip
  ansible.builtin.command:
    cmd: unzip -q /beegfs/dataset/music-classification-wav.zip -d /beegfs/dataset/
  args:
    creates: /beegfs/dataset/TRAIN_V2 
  become: true

- name: Clean up the massive zip file to save storage space
  ansible.builtin.file:
    path: /beegfs/dataset/music-classification-wav.zip
    state: absent
  become: true

- name: Copy preprocess dataset file
  ansible.builtin.copy:
    src: /home/almalinux/comp0239_cw/src/preprocess_dataset.py
    dest: /home/almalinux/comp0239_cw/src/preprocess_dataset.py
    mode: '0755'
  become: true

- name: Run the dataset preprocessing script
  ansible.builtin.command:
    cmd: python3 /home/almalinux/comp0239_cw/src/preprocess_dataset.py
  args:
    creates: /beegfs/dataset/audio_files  # FIX: Prevents the script from running twice
  become_user: almalinux                  # FIX: Ensures files are owned by almalinux, not root

- name: Generate the master list of wav files for Slurm
  ansible.builtin.shell: 
    cmd: find /beegfs/dataset/audio_files -name "*.wav" > /beegfs/dataset/master_list.txt
  become: true
  become_user: almalinux